# -*- coding: utf-8 -*-
"""Tarea 03 - NGNF. Martina Núñez

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TNreyjqpGuovICAK_s-L1Kq4kO58t-tp

Se elaborará una tabla para representar los 5 días de la semana en los que dedico tiempo a la actividad física, a saber, lunes, martes, miércoles, jueves y viernes. En este caso, la actividad física es la danza, específicamente folclórica (cueca).

La tabla incluirá una columna para los días y, adicionalmente, una columna para las horas dedicadas a esta actividad en cada día. Por último, habrá una fila que mostrará el total de horas dedicadas al baile durante estos 5 días.
"""

import pandas as pd

#Aquí creamos un diccionario llamado data que contiene los datos que queremos mostrar en la tabla (días y horas destinadas a la actividad).
#El diccionario tiene dos claves ("Días" y "Horas de Danza") y sus valores asociados son listas que contienen los nombres de los días y las horas respectivamente.
#La última entrada en el diccionario es "Total", que se calcula sumando las horas de danza folclórica usando sum([...]).
data = {
    'Días': ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Total'],
    'Horas de Danza': [3, 1, 3, 4, 5, sum([3, 1, 3, 4, 5])]
}

#Creamos un DataFrame de Pandas a partir del diccionario data.
#En este caso, el DataFrame se crea con dos columnas: "Días" y "Horas de Danza", y los datos se toman del diccionario data.
df = pd.DataFrame(data)

#Agregamos "hora" o "horas" como sufijo a los números en la columna de "Horas de Danza"
#df['Horas de Danza'].apply(...) se utiliza para aplicar una función a cada elemento de la serie o columna.
#lambda x: f'{x} hora' if x == 1 else f'{x} horas' la función toma un argumento x (cada valor en la columna "Horas de Danza") y, según el valor de x, devuelve una cadena que agrega "hora" o "horas" al número x. Si x es igual a 1, la función devuelve f'{x} hora', lo que significa que si el valor en la columna es 1, se agrega "hora" en singular. De lo contrario, si x no es igual a 1, la función devuelve f'{x} horas', lo que significa que para cualquier otro valor diferente de 1, se agrega "horas" en plural.
df['Horas de Danza'] = df['Horas de Danza'].apply(lambda x: f'{x} hora' if x == 1 else f'{x} horas')

#Imprimimos la tabla para ver si esta correcto
print(df)

#Guardamos el DataFrame como un archivo CSV en nuestro Google Drive
csv_filename = '/content/drive/MyDrive/NARRACIÓN GRÁFICA DE NO FICCIÓN/tabla_horas_danza.csv'
df.to_csv(csv_filename, index=False)