# -*- coding: utf-8 -*-
"""Tarea_02 - NGN. Martina Núñez

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mn9GIrwBeDv_ENFy3KWhSkvV8iQkjtdS

**Problema 1.**

Hacer un programa que imprima los números del 1 al 100.
"""

for x in range(100): #Utilicé "for" para la estructura de repetición, mientras que "range" lo utilicé para indicar el rango necesario en números enteros, que en este caso es llegar o imprimir hasta el número 100.
  print(x+1) #Utilizar en este caso "(x+1)" me sirvió para que, al momento de imprimir, se incluyeran los números dentro del rango establecido del 1 al 100. Sin el "+1", consideraría el número 0 y llegaría solo hasta el 99, lo cual no es lo que necesito.

"""**Problema 2.**

Hacer un programa que imprima los números del 1 al 100 que sean divisibles entre 3 (con resto 0)
"""

for x in range(100):
  if(x+1) % 3 == 0: #Con respecto al caso anterior, aquí está la única parte que agregué como novedad. En esta parte, el "if" funciona como estructura condicional para el caso establecido. Al agregar "%3", se indica que debe ser divisible por 3, mientras que "==0" significa "con resto igual a 0". Esto contribuye a la resolución del problema.
    print(x+1)

"""**Problema 3.**

Realiza el algoritmo para un sumador de dos números. Si el resultado es menor a 100 se mostrará el mensaje "menor a 100", si el resultado es mayor a 100, pero menor a 150 mostrará el mensaje "mayor a 100", pero si es mayor a 150 mostrará el mensaje "mayor a 150".
"""

numero_1 = int(input("Ingresa un número")) #Utilicé "int" para trabajar con números enteros, que es lo que requiere el problema. Mientras que "input" funciona para que el usuario ingrese algún número.
numero_2 = 5
suma = numero_1 + numero_2
resultado = ""

if(suma<100): #De aquí en adelante, el "if" y los dos "elif" funcionan como condicionales, comprobando si el número es menor que 100, mayor que 100 o mayor que 150, dependiendo a lo que indique el usuario.
  resultado = "menor a 100"
elif(suma>=100 and suma<150):
  resultado = "mayor a 100"
elif(suma>=150):
  resultado = "mayor a 150"

print(resultado)

"""**Problema 4.**

Generar un programa que combine variables, tipos de datos y una condicional en Python (hacer una función que evalúe si el usuario es mayor de edad y si le gusta la programación, que envíe diferentes textos según la respuesta del usuario)
"""

edad = int(input("Por favor, ingrese su edad: ")) #Utilicé "int" para trabajar con números enteros, que es lo que requiere el problema. Mientras que "input" funciona para que el usuario ingrese su edad.
le_gusta_la_programacion = input("¿Te gusta la programación? (Si/No): ") #Con el "input", el usuario podrá responder a la pregunta si le gusta la programación con un "si" o un "no".

if edad >= 18 and le_gusta_la_programacion == "si":
  print("¡Súper! Eres mayor de edad y te gusta la programación.") #Con el "if" y el "print" de esta parte, si el usuario tiene 18 años o más y respondió que sí le gusta la programación, se mostrará el mensaje establecido.
elif edad >= 18 and le_gusta_la_programacion == "no":
  print("¡Oh! Eres mayor de edad, pero no te gusta la programación. Está bien :(") #Con el "elif" y el "print" de esta parte, si el usuario tiene 18 años o más y respondió que no le gusta la programación, se mostrará el mensaje establecido.
elif edad < 18 and le_gusta_la_programacion == "si":
  print("¡Wow! Eres menor de edad y te gusta la programación. Genial :)") #Con el "elif" y el "print" de esta parte, si el usuario tiene menos de 18 años y respondió que si le gusta la programación, se mostrará el mensaje establecido.
else:
  print("Eres menor de edad y no te gusta la programación. Está bien, explora tus gustos.") #Con el "else" y el "print" de esta parte, si el usuario tiene menos de 18 años y respondió que no le gusta la programación, se mostrará el mensaje establecido.