# -*- coding: utf-8 -*-
"""Tarea 04 - NGNF. Martina Núñez

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n8fEdZL28i4SOeUDxLv4ABjdphiEhM5v

Generaremos un gráfico de líneas con la libreria Pandas para representar la información de la tabla que creamos en la Tarea 03. Esta tabla detalla las horas semanales dedicadas a la danza folclórica, una de mis actividades recreativas más habituales, realizada durante 5 días a la semana.
"""

#Cargamos el archivo CSV que creamos en la Tarea 03 para utilizarlo en nuestro trabajo

import pandas as pd

CSV_Horas_semanales_danza = "/content/drive/MyDrive/Colab Notebooks/tabla_horas_semanales_danza.csv"

#Leemos el archivo CSV en un DataFrame
df = pd.read_csv(CSV_Horas_semanales_danza)

import pandas as pd

#Leemos el archivo CSV en un DataFrame
CSV_Horas_semanales_danza = "/content/drive/MyDrive/Colab Notebooks/tabla_horas_semanales_danza.csv"
df = pd.read_csv(CSV_Horas_semanales_danza, encoding='utf-8') #Usamos Pandas para leer el archivo CSV y crear un DataFrame llamado "df" que contendrá nuestros datos.
                                                              #El parámetro "encoding" se establece en 'utf-8' para garantizar que se interpreten correctamente los caracteres especiales.

#Convertir las "Horas totales en danza" a valores numéricos enteros
df["Horas totales en danza"] = df["Horas totales en danza"].str.extract('(\d+)').astype(int) #En esta línea, extraemos solo los dígitos de la columna "Horas totales en danza" y convertimos el resultado a valores enteros (números enteros) en el DataFrame.

#Excluir la fila que contiene el total
df = df[df["Días"] != "Total"] #Filtramos el DataFrame para excluir la fila que contiene la palabra "Total" en la columna "Días".

#Configurar el índice del DataFrame
df.set_index("Días", inplace=True) # Configuramos la columna "Días" como el índice del DataFrame. Esto facilitará la creación del gráfico utilizando los días de la semana como etiquetas del eje X.

#Crear un gráfico de líneas agrupadas
ax = df[["Horas totales en danza"]].plot(kind="line", marker='o', figsize=(10, 6), legend=False) #Creamos un gráfico de líneas utilizando la columna "Horas totales en danza" del DataFrame.
                                                                                                 #Configuramos el estilo del gráfico con líneas sólidas y marcadores circulares ("o").
                                                                                                 #También definimos el tamaño del gráfico y desactivamos la leyenda.

#Personalizar el gráfico
plt.title("Horas Totales en Danza por Día de la Semana") #Agregamos un título al gráfico.
plt.xlabel("Día de la Semana") #Agregamos una etiqueta al eje X del gráfico.
plt.ylabel("Horas Totales en Danza") #Agregamos una etiqueta al eje Y del gráfico.
plt.xticks(rotation=0)  #Rotamos las etiquetas del eje X para mejorar la legibilidad.

#Guardamos el gráfico en nuestro Google Drive
ruta_guardado = "/content/drive/My Drive/Gráficos/grafico_horas_danza.png"
plt.savefig(ruta_guardado, format="png")

#Mostramos el gráfico para ver como es que quedo.
plt.show()

